name: ep
services:
  mysql:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db
      MYSQL_ROOT_PASSWORD: db
    volumes:
      - ./data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
  api:
    image: node:latest
    ports:
      - 8080:8080
    environment:
      DB_HOST: mysql
      DB_NAME: db
      DB_USER: db
      DB_PASSWORD: db
      DB_DIALECT: mariadb
    volumes:
      - ./api:/api
    working_dir: /api
    depends_on:
      mysql:
        condition: service_healthy
    command: bash -c "npm i && npm run migrate && npm start"
  app:
    image: node:latest
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
    working_dir: /app
    depends_on:
      - api
    command: bash -c "npm i && npm start"